f=open('file.txt','r')
print(f"cursor pos  ={f.tell()}")
print("before seek mtd")
f.seek(0)
#print(f.read())
#print(f.readline())
#print(f.readline())
lines=f.readlines()
print(len(lines))
for i in lines[0:1]:
    print (i,end="")
print("after seek mtd")
print(f"cursor pos ={f.tell()}")
print(f.name)
print(f.closed)
f.close()
print(f.closed)